export const chartBoxUser = {
  title: "Total Benefeciaries",
  number: 2304,
  dataKey: "benefeciaries",
  percentage: 60,
  chartData: [
    { name: "Sun", benefeciaries: 2 },
    { name: "Mon", benefeciaries: 1 },
    { name: "Tue", benefeciaries: 5 },
    { name: "Wed", benefeciaries: 3 },
    { name: "Thu", benefeciaries: 2 },
    { name: "Fri", benefeciaries: 10 },
    { name: "Sat", benefeciaries: 6 },
  ],
};
export const chartBoxLivestocks = {
  title: "Total Livestocks",
  number: 2304,
  dataKey: "benefeciaries",
  percentage: 60,
  chartData: [
    { name: "Sun", benefeciaries: 60 },
    { name: "Mon", benefeciaries: 90 },
    { name: "Tue", benefeciaries: 120 },
    { name: "Wed", benefeciaries: 100 },
    { name: "Thu", benefeciaries: 166 },
    { name: "Fri", benefeciaries: 180 },
    { name: "Sat", benefeciaries: 444 },
  ],
};
export const chartBoxDispersal = {
  title: "Total Dispersal",
  number: 2304,
  dataKey: "benefeciaries",
  percentage: 60,
  chartData: [
    { name: "Sun", benefeciaries: 20 },
    { name: "Mon", benefeciaries: 15 },
    { name: "Tue", benefeciaries: 12 },
    { name: "Wed", benefeciaries: 20 },
    { name: "Thu", benefeciaries: 16 },
    { name: "Fri", benefeciaries: 18 },
    { name: "Sat", benefeciaries: 44 },
  ],
};
export const chartBoxRedispersal = {
  title: "Total Redispersal Rate",
  number: 2304,
  dataKey: "benefeciaries",
  percentage: 60,
  chartData: [
    { name: "Sun", benefeciaries: 20 },
    { name: "Mon", benefeciaries: 15 },
    { name: "Tue", benefeciaries: 12 },
    { name: "Wed", benefeciaries: 20 },
    { name: "Thu", benefeciaries: 16 },
    { name: "Fri", benefeciaries: 18 },
    { name: "Sat", benefeciaries: 44 },
  ],
};
export const Benef = [
  {
      "ID" : "01",
      "Barangay" : " BUCAL",
      "Name" : "Michael Pagcaliwagan",
      "Birthdate" : " 29/09/1977 ",
      "ContactNumber" : " 09474616380 " ,
  },
  {
      "ID" : "02",
      "Barangay" : " BUCAL ",
      "Name" : " Romel Abrinica ",
      "Birthdate" : " 19/06/1983 ",
      "ContactNumber" : " 09913372121 " ,
  },
  {
      "ID" : "03",
      "Barangay" : " MAHABANG PARANG ",
      "Name" : " Edgardo Talabis ",
      "Birthdate" : " 11/07/1965 ",
      "ContactNumber" : " 09194539981 " ,
  },
  {
      "ID" : "04",
      "Barangay" : " MAHABANG PARANG ",
      "Name" : " Dancel Fragada ",
      "Birthdate" : " 25/08/1975 ",
      "ContactNumber" : " 09054035312 " ,
  },
  {
      "ID" : "05",
      "Barangay" : " MAHABANG PARANG ",
      "Name" : " Ricardo Noriega ",
      "Birthdate" : " 07/02/1972 ",
      "ContactNumber" : " 09217534398 " ,
  },
  {
      "ID" : "06",
      "Barangay" : " SAN JOSE SICO ",
      "Name" : " Delmundo Manalo ",
      "Birthdate" : " 01/09/1966 ",
      "ContactNumber" : " 09385318691 " ,
  },
  {
      "ID" : "07",
      "Barangay" : "  SAN JOSE SICO ",
      "Name" : " Elaine Joy Magsino ",
      "Birthdate" : " 22/09/1997 ",
      "ContactNumber" : " 09385318691 " ,
  },
  {
      "ID" : "08",
      "Barangay" : " SAN JOSE SICO ",
      "Name" : " Antonio De Castro Jr. ",
      "Birthdate" : " 19/04/1982 ",
      "ContactNumber" : " 09563576191 " ,
  },
  {
      "ID" : "09",
      "Barangay" : " PAHARANG KANLURAN ",
      "Name" : " Jerry Villena ",
      "Birthdate" : " 29/04/1973 ",
      "ContactNumber" : " 09279475203 " ,
  },
  {
      "ID" : "10",
      "Barangay" : " PAHARANG KANLURAN ",
      "Name" : " Rosel Liwag ",
      "Birthdate" : " 03/10/1976 ",
      "ContactNumber" : " 09102418785 " ,
  }
] 
export const Livestock = [{

  "ID" : "2023-01",
  "Breed" : " Ongole cattle ",
  "AnimalType" : " Cattle ",
  "Status/Alive" : "",
  "Health" : "",
},
{
  "ID" : "2023-02",
  "Breed" : " Ongole cattle ",
  "AnimalType" : " Cattle ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-03",
  "Breed" : " Ongole cattle ",
  "AnimalType" : " Cattle ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-04",
  "Breed" : " Plymouth Rock chicken ",
  "AnimalType" : " Free Range Chicken ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-05",
  "Breed" : " Plymouth Rock chicken ",
  "AnimalType" : " Free Range Chicken ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-06",
  "Breed" : " Australorp ",
  "AnimalType" : " Free Range Chicken ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-07",
  "Breed" : " Anglo-Nubian goat ",
  "AnimalType" : " Goat - Doe ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-08",
  "Breed" : " Anglo-Nubian goat ",
  "AnimalType" : " Goat - Doe ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-09",
  "Breed" : " Anglo-Nubian goat ",
  "AnimalType" : " Goat - Doe ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},
{
  "ID" : "2023-010",
  "Breed" : " Enviropig ",
  "AnimalType" : " Swine ",
  "Status/Alive" : " Yes ",
  "Health" : "",
},

]
