export const Benefeciaries = [
  {
    ID: "01",
    Barangay: " BUCAL",
    Name: "Michael Pagcaliwagan",
    Birthdate: " 29/09/1977 ",
    ContactNumber: " 09474616380 ",
  },
  {
    ID: "02",
    Barangay: " BUCAL ",
    Name: " Romel Abrinica ",
    Birthdate: " 19/06/1983 ",
    ContactNumber: " 09913372121 ",
  },
  {
    ID: "03",
    Barangay: " MAHABANG PARANG ",
    Name: " Edgardo Talabis ",
    Birthdate: " 11/07/1965 ",
    ContactNumber: " 09194539981 ",
  },
  {
    ID: "04",
    Barangay: " MAHABANG PARANG ",
    Name: " Dancel Fragada ",
    Birthdate: " 25/08/1975 ",
    ContactNumber: " 09054035312 ",
  },
  {
    ID: "05",
    Barangay: " MAHABANG PARANG ",
    Name: " Ricardo Noriega ",
    Birthdate: " 07/02/1972 ",
    ContactNumber: " 09217534398 ",
  },
  {
    ID: "06",
    Barangay: " SAN JOSE SICO ",
    Name: " Delmundo Manalo ",
    Birthdate: " 01/09/1966 ",
    ContactNumber: " 09385318691 ",
  },
  {
    ID: "07",
    Barangay: "  SAN JOSE SICO ",
    Name: " Elaine Joy Magsino ",
    Birthdate: " 22/09/1997 ",
    ContactNumber: " 09385318691 ",
  },
  {
    ID: "08",
    Barangay: " SAN JOSE SICO ",
    Name: " Antonio De Castro Jr. ",
    Birthdate: " 19/04/1982 ",
    ContactNumber: " 09563576191 ",
  },
  {
    ID: "09",
    Barangay: " PAHARANG KANLURAN ",
    Name: " Jerry Villena ",
    Birthdate: " 29/04/1973 ",
    ContactNumber: " 09279475203 ",
  },
  {
    ID: "10",
    Barangay: " PAHARANG KANLURAN ",
    Name: " Rosel Liwag ",
    Birthdate: " 03/10/1976 ",
    ContactNumber: " 09102418785 ",
  },
];

export const Livestockk = [
  {
    ID: "2023-01",
    Breed: " Ongole cattle ",
    AnimlType: " Cattle ",
    StatusAlive: "",
    Health: "",
  },
  {
    ID: "2023-02",
    Breed: " Ongole cattle ",
    AnimlType: " Cattle ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-03",
    Breed: " Ongole cattle ",
    AnimlType: " Cattle ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-04",
    Breed: " Plymouth Rock chicken ",
    AnimlType: " Free Range Chicken ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-05",
    Breed: " Plymouth Rock chicken ",
    AnimlType: " Free Range Chicken ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-06",
    Breed: " Australorp ",
    AnimlType: " Free Range Chicken ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-07",
    Breed: " Anglo-Nubian goat ",
    AnimlType: " Goat - Doe ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-08",
    Breed: " Anglo-Nubian goat ",
    AnimlType: " Goat - Doe ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-09",
    Breed: " Anglo-Nubian goat ",
    AnimlType: " Goat - Doe ",
    StatusAlive: " Yes ",
    Health: "",
  },
  {
    ID: "2023-010",
    Breed: " Enviropig ",
    AnimlType: " Swine ",
    StatusAlive: " Yes ",
    Health: "",
  },
];
