export const livestocks = [
  {
    ID: "2023-01",
    Breed: " Ongole cattle ",
    AnimalType: " Cattle ",
    StatusAlive: "Yes",
    Age: "3 Months",
    Health: "Unknown",
  },
  {
    ID: "2023-02",
    Breed: " Ongole cattle ",
    AnimalType: " Cattle ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-03",
    Breed: " Ongole cattle ",
    AnimalType: " Cattle ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Unknown",
  },
  {
    ID: "2023-04",
    Breed: " Plymouth Rock chicken ",
    AnimalType: " Free Range Chicken ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-05",
    Breed: " Plymouth Rock chicken ",
    AnimalType: " Free Range Chicken ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-06",
    Breed: " Australorp ",
    AnimalType: " Free Range Chicken ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-07",
    Breed: " Anglo-Nubian goat ",
    AnimalType: " Goat - Doe ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-08",
    Breed: " Anglo-Nubian goat ",
    AnimalType: " Goat - Doe ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-09",
    Breed: " Anglo-Nubian goat ",
    AnimalType: " Goat - Doe ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
  {
    ID: "2023-010",
    Breed: " Enviropig ",
    AnimalType: " Swine ",
    StatusAlive: " Yes ",
    Age: "4 Months",
    Health: "Healthy",
  },
];
export type Livestock = (typeof livestocks)[number];
